### ISSUE TITLE
Can't be used with RKA Slim Session Middleware

### ISSUE THREAD

**Issue by aurmil** [kanellov/slim-twig-flash#2]
I'm looking for a a clean solution if someone has an idea

using [RKA Slim Session Middleware](https://github.com/akrabat/rka-slim-session-middleware) + [Slim Framework Flash Messages](https://github.com/slimphp/Slim-Flash) + [Slim Twig Flash](https://github.com/kanellov/slim-twig-flash)

for session middleware:
```php
$app->add(new RKA\SessionMiddleware(...));
```

for Slim Flash:
```php
$container['flash'] = function () {
    return new Slim\Flash\Messages();
};
```

for Slim Twig Flash:
```php
$container['view'] = function ($container) {
    ...

    $view->addExtension(new Knlv\Slim\Views\TwigMessages(
        $container->flash
    ));

    return $view;
};
```

$container->flash calls new Slim\Flash\Messages() which tries to access $_SESSION which is not yet created by middleware

ping @akrabat

**Comment by kanellov** [comment]
Hi @aurmil. I think the problem is that session starts in a middleware. `Slim\Flash\Messages` tries to access `$_SESSION` before `session_start()`. You could try registering twig extension in a middleware, which is invoked after `RKA\SessionMiddleware`. Something like this:

```php
$app->add(function($request, $response, $next) use ($container) {
    $view = $container['view'];
    $view->addExtension(new Knlv\Slim\Views\TwigMessages(
        $container->flash
    ));
    return $next($request, $response);
});

**Comment by aurmil** [comment]
Hi,
good news for me we share the same thoughts about what's happening
good idea to add extension in middleware too!
just don't forget to return the response
thanks

**Comment by kanellov** [comment]
Thanx for the debuging ;-) ...
